version: '3'
services:
  bird-tracker-dev:
    stdin_open: true
    tty: true
    container_name: bird-tracker-dev
    ports:
      - "5000:5000"
    build:
      context: .
      dockerfile: _docker/Dockerfile
    volumes:
      - ./:/app/
    devices:
      - /dev/video0:/dev/video0

networks:
  default:
    name: bird-tracker-dev
