class_ind = {0: 'American Crow',
             1: 'American Robin',
             2: 'Black-crested Titmouse',
             3: 'Blue Jay',
             4: 'Carolina Chickadee',
             5: 'Common Grackle',
             6: 'Eastern Phoebe',
             7: 'House Wren',
             8: 'Ladder-backed woodpecker',
             9: 'Northern Cardinal',
             10: 'Northern Flicker',
             11: 'Northern Mockingbird',
             12: 'Squirrel',
             13: 'Tufted Titmouse',
             14: 'White-crowned Sparrow',
             15: 'White-winged Dove'}
