name: build docker images

on:
  push:

jobs:

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ github.workspace }}//_docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          context: ${{ github.workspace }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bird-tracker:latest

  build-tagged-docker:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: ${{ github.workspace }}/_docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          context: ${{ github.workspace }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bird-tracker:${{ github.ref_name }}
