version: '3'
services:
  app:
    container_name: bird-tracker
    image: 'boscho87/bird-tracker:latest'
    volumes:
      - ./data:/app/data
    environment:
      - DB_FILE_PATH="/app/data/bird-tracker.db"
    devices:
      - /dev/video0:/dev/video0
